---
title: "About Xavier's blog"
description: |
author:
  - name: Xavier Prat-Resina 
    url: https://pratresina.umn.edu
    affiliation: University of Minnesota Rochester
    affiliation_url: https://r.umn.edu
    orcid_id: 0000-0002-1380-6025
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

My name is [Xavier Prat-Resina](https://pratresina.umn.edu) and I am an Associate Professor of Chemistry at the University of Minnesota Rochester [(UMR)](https://r.umn.edu). I enjoy coding for data analysis, web design, and molecular modelling.

This is just a collection of musings, half-cooked analysis with python/R scripts, and reports that could have been submitted to a journal... and never did. 
The place where all the projects come to die. Too often I start a research question, a project or a data analysis that has the potential to become a paper. 
And then a new fire needs to be put out and the results remain among my notes, to never see the light again.
Well, this is an unfiltered version of those notes. Keep in mind, they're dead.

This site is built using the [Distill](https://rstudio.github.io/distill/) library available on RStudio where I type Markdown plain text, *knit* it, and submit it to github. 
I'm pretty old school and I still prefer plain-text files where I can use the *vim* commands to edit them and SHELL commands on the terminal.